{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "kuryr.fullname" . }}-controller
  labels:
    {{- include "kuryr.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    verbs: ["*"]
    resources:
      - endpoints
      - pods
      - nodes
      - services
      - services/status
      - namespaces
  - apiGroups:
      - openstack.org
    verbs: ["*"]
    resources:
      - kuryrnets
      - kuryrnetworks
      - kuryrnetpolicies
      - kuryrnetworkpolicies
      - kuryrloadbalancers
      - kuryrports
  - apiGroups: ["networking.k8s.io"]
    resources:
      - networkpolicies
    verbs:
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups: ["k8s.cni.cncf.io"]
    resources:
      - network-attachment-definitions
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "kuryr.fullname" . }}-cni
  labels:
    {{- include "kuryr.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    verbs: ["*"]
    resources:
      - pods
      - nodes
  - apiGroups:
      - openstack.org
    verbs: ["*"]
    resources:
      - kuryrports
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "kuryr.fullname" . }}-controller
  labels:
    {{- include "kuryr.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ template "kuryr.controller.serviceAccountName" . }}
    namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "kuryr.fullname" . }}-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "kuryr.fullname" . }}-cni
  labels:
    {{- include "kuryr.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ template "kuryr.cni.serviceAccountName" . }}
    namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "kuryr.fullname" . }}-cni
{{- end -}}
