{{- if .Values.controller.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kuryr.controller.serviceAccountName" . }}
  namespace: kube-system
  {{- with .Values.controller.serviceAccount.annotations -}}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
